# Generated by Django 3.1 on 2020-10-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsmenu',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
