# Generated by Django 3.1 on 2020-10-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_rolesforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesforma',
            name='id_status',
            field=models.BigIntegerField(default=1),
        ),
    ]
