# Generated by Django 3.1 on 2020-10-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_auto_20201012_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesforma',
            name='id_status',
            field=models.IntegerField(default=1),
        ),
    ]
