# Generated by Django 3.1 on 2020-10-16 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formas', '0002_formsmenu_enabled'),
        ('roles', '0006_auto_20201016_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesforma',
            name='id_forma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_forma', to='formas.formsmenu'),
        ),
        migrations.AlterField(
            model_name='rolesforma',
            name='id_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_role', to='roles.role'),
        ),
    ]
