# Generated by Django 3.1 on 2020-10-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formas', '0002_formsmenu_enabled'),
        ('roles', '0007_auto_20201016_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='forma',
            field=models.ManyToManyField(to='formas.FormsMenu'),
        ),
    ]
