# Generated by Django 3.1 on 2020-10-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formas', '0002_formsmenu_enabled'),
        ('roles', '0009_auto_20201016_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='forma',
        ),
        migrations.AddField(
            model_name='role',
            name='forma',
            field=models.ManyToManyField(to='formas.FormsMenu'),
        ),
    ]
