# Generated by Django 3.1 on 2020-10-18 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formas', '0002_formsmenu_enabled'),
        ('roles', '0013_auto_20201017_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='formas',
            field=models.ManyToManyField(related_name='formas', to='formas.FormsMenu'),
        ),
        migrations.RemoveField(
            model_name='rolesforma',
            name='id_forma',
        ),
        migrations.AddField(
            model_name='rolesforma',
            name='id_forma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_forma', to='formas.formsmenu'),
        ),
    ]
