# Generated by Django 3.1 on 2020-10-18 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0015_auto_20201018_1147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RolesForma',
        ),
    ]
